Repository TamTamBot/TamTamGitHubBot, pull requests merged in 2019-10, with the labels that each got.

#2 Fix pull request message
  src/main/java/com/github/senyast4745/testbot/models/GitHubPullRequestEvent.java
Labels: enhancement

#3 Fix README 2
  README.md
Labels: enhancement

#27 Correct Add readme
  .gitignore
  README.md
  src/main/java/com/github/testbot/bot/WebhookBot.java
Labels: documentation

#28 implement unsubscribe from repos and deleting dead webhooks
  src/main/java/com/github/testbot/bot/WebhookBot.java
  src/main/java/com/github/testbot/constans/BotCommands.java
  src/main/java/com/github/testbot/constans/ChatStates.java
  src/main/java/com/github/testbot/github/CustomHttpClient.java
  src/main/java/com/github/testbot/github/WebhookGitHub.java
  src/main/java/com/github/testbot/interfaces/BotTexts.java
  src/main/java/com/github/testbot/interfaces/GitHubActions.java
  src/main/java/com/github/testbot/models/github/GitHubRepositoryModel.java
  src/main/java/com/github/testbot/parsers/CommandParser.java
Labels: enhancement

#30 Add bash script to start/stop/restart bot
  build.gradle
  src/main/java/com/github/testbot/bot/WebhookBot.java
  src/main/resources/application.properties
  src/main/scripts/startBot.sh
Labels: deploy
